let stockProductos = [
    {id: 1, nombre: "Intel Core i7 10ma gen", tipo: "procesador", precio: 2000, socket: "LGA1200", img: '/assets/img/i7_10th_gen.jpg'},
    {id: 2, nombre: "Intel Core i7 11va gen", tipo: "procesador", precio: 3000, socket: "LGA1200", img: '/assets/img/i7_11th_gen.jpg'},
    {id: 3, nombre: "Intel Core i7 12va gen", tipo: "procesador", precio: 4000, socket: "LGA1700", img: '/assets/img/i7_12th_gen.jpg'},
    {id: 4, nombre: "Memoria RAM 8GB DDR4 2666Mhz", tipo: "RAM", precio: 500, img: '/assets/img/8gb_ram.jpg'},
    {id: 5, nombre: "Memoria RAM 16GB DDR4 3200Mhz", tipo: "RAM", precio: 750, img: '/assets/img/16gb_ram_rgb.jpg'},
    {id: 6, nombre: "Motherboard  H410M H V3", tipo: "motherboard", precio: 1300, img: '/assets/img/mother_10gen_intel.jpg'},
    {id: 7, nombre: "Motherboard MSI H510M-A PRO", tipo: "motherboard", precio: 1400 , img: '/assets/img/mother_11gen.jpg'},
    {id: 8, nombre: "Motherboard MSI PRO B660M-A WIFI DDR4", tipo: "motherboard", precio: 1500 , img: '/assets/img/mother_12gen_intel.jpg'},
    {id: 9, nombre: "Placa de video RTX 3060", tipo: "grafica", precio: 2500 , img: '/assets/img/3060.jpg'},
    {id: 10, nombre: "Placa de video RTX 3070", tipo: "grafica", precio: 4200 , img: '/assets/img/3070.jpg'},
    {id: 11, nombre: "Placa de video RTX 3080", tipo: "grafica", precio: 6500 , img: '/assets/img/3080.jpg'},
    {id: 12, nombre: "Fuente de alimentación Gigabyte 550w 80+ Bronze", tipo: "psu", precio: 1000 , img: '/assets/img/fuente_550w.jpg'},
    {id: 13, nombre: "Fuente de alimentación Gigabyte 1000w 80+ Gold", tipo: "psu", precio: 1650 , img: '/assets/img/fuente_1000w.jpg'},
    {id: 14, nombre: "Disco duro de 1TB WD Blue", tipo: "disco duro", precio: 300 , img: '/assets/img/1tb_hdd.jpg'},
    {id: 15, nombre: "Disco sólido de 1TB NVME M2", tipo: "disco sólido nvme", precio: 1150 , img: '/assets/img/1tb_nvmessd.jpg'},
    {id: 16, nombre: "Disco sólido de 1TB 2.5", tipo: "disco sólido 2.5", precio: 750 , img: '/assets/img/1tb_ssd.jpg'},
    {id: 17, nombre: "Gabinete jorge", tipo: "gabinete", precio: 200 , img: '/assets/img/gabinete1.jpg'},
    {id: 18, nombre: "Gabinete jorgito", tipo: "gabinete", precio: 220 , img: '/assets/img/gabinete2.jpg'},
]